name: Build and Release to GitHub

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]*'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.16'

      - name: Build binaries
        run: make all

      - name: Generate changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make changelog

      - name: Normalize changelog format
        run: |
          sed -i.bak -E 's/^##([ ]+)\[v([0-9])/##\1\[\2/' CHANGELOG.md
          rm CHANGELOG.md.bak

      - name: Create GitHub Release
        uses: antonyurchenko/git-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "true"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_PREFIX: "Release: "
        with:
          args: |
            .bin/*.tar.gz
            .bin/*.zip
