name: Test
on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'
    paths-ignore:
      - 'docs/**'
      - '*.md'

  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Install Node
        uses: actions/setup-node@v2
        with:
            node-version: '16'

      - name: Test Signal Forwarding (Linux)
        if: runner.os == 'Linux'
        run: |          
          make build/linux_amd64
          cp .bin/inject test/signals/bin
          cd test/signals
          yarn install --frozen-lockfile
          yarn build
          yarn start

      - name: Test Signal Forwarding (macOS)
        if: runner.os == 'macOS'
        run: |
          make build/darwin_amd64
          cp .bin/inject test/signals/bin
          cd test/signals
          yarn install --frozen-lockfile
          yarn build
          yarn start
